#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/YunDesk/YunDesk /usr/bin/YunDesk
	
	if [ "systemd" == "$INITSYS" ]; then

	if [ -e /etc/systemd/system/YunDesk.service ]; then
		rm /etc/systemd/system/YunDesk.service /usr/lib/systemd/system/YunDesk.service /usr/lib/systemd/user/YunDesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
	cp /usr/share/YunDesk/files/systemd/YunDesk.service /usr/lib/systemd/system/YunDesk.service
		# try fix error in Ubuntu 18.04
	# Failed to reload YunDesk.service: Unit YunDesk.service is not loaded properly: Exec format error.
	# /usr/lib/systemd/system/YunDesk.service:10: Executable path is not absolute: pkill -f "YunDesk --"
		if [ -e /usr/bin/pkill ]; then
		sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/YunDesk.service
		fi
		systemctl daemon-reload
	systemctl enable YunDesk
	systemctl start YunDesk
	fi
fi
