#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/RustDesk/RustDesk /usr/bin/RustDesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/RustDesk.service ]; then
			rm /etc/systemd/system/RustDesk.service /usr/lib/systemd/system/RustDesk.service /usr/lib/systemd/user/RustDesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/RustDesk/files/systemd/RustDesk.service /usr/lib/systemd/system/RustDesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload RustDesk.service: Unit RustDesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/RustDesk.service:10: Executable path is not absolute: pkill -f "RustDesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/RustDesk.service
		fi
		systemctl daemon-reload
		systemctl enable RustDesk
		systemctl start RustDesk
	fi
fi
